In [2]:
import numpy as np

## Boston Housing Dataset

이번 과제는 보스턴시의 주택 가격과 관련 데이터를 활용하여 보스턴 시의 집값을 예측하는 문제를 푸는 것입니다. Single-layer Neural Network를 활용하여 보스턴의 집값을 예측하는 알고리즘을 구현하세요.

각 컬럼에 대한 설명은 다음과 같습니다. 출처: [ai-times](http://ai-times.tistory.com/431 [ai-times])

  * **CRIM**: 자치 시(town) 별 1인당 범죄율
  * **ZN**: 25,000 평방피트를 초과하는 거주지역의 비율
  * **INDUS**: 비소매상업지역이 점유하고 있는 토지의 비율
  * **CHAS**: 찰스강의 경계에 위치해 있으면 1, 그렇지 않으면 0
  * **NOX**: 10ppm당 농축 일산화질소
  * **RM**: 주택 1가구당 평균 방의 개수
  * **AGE**: 1940년 이전에 건축된 소유주택의 비율
  * **DIS**: 5개의 보스턴 직업센터까지의 접근성 지수
  * **RAD**: 방사형 도로까지의 접근성 지수
  * **TAX**: 10,000 달러 당 재산세율
  * **PTRATIO**: 자치 시(town)별 학생/교사 비율
  * **B**: 1000(Bk-0.63)^2, 여기서 Bk는 자치시별 흑인의 비율을 말함.
  * **LSTAT**: 모집단의 하위계층 비율(%)
  * **MEDV**: 본인 소유의 주택가격(중앙값) (단위: $1,000)
  
** 주의 사항 **
  * **MEDV**가 label(y), 나머지가 feature(X)라고 가정하고 문제를 풀어주세요.
  * **한 번에 너무 잘 풀려는 시도를 하지 마세요.** 처음에는 어떻게든 동작하는 코드를 만드는데 집중하고, 그 다음에 코드를 개성하세요.
  * 현실 데이터는 이전에 우리가 다룬 가상의 데이터와 다르기 때문에, error가 0에 가깝게 내려가지 않을 수도 있습니다. (```error = np.abs(y_predict - y).mean()```) **Boston Housing Dataset에서 error는 5 미만으로 내려가면 충분합니다. ** (=$5,000)
  * error가 수렴하지 않고 발산한다면, **learning_rate를 작게 조정해보세요**.

In [3]:
from sklearn.datasets import load_boston

boston = load_boston()

In [4]:
X = boston["data"]

print(X.shape)
X[0]

(506, 13)


array([6.320e-03, 1.800e+01, 2.310e+00, 0.000e+00, 5.380e-01, 6.575e+00,
       6.520e+01, 4.090e+00, 1.000e+00, 2.960e+02, 1.530e+01, 3.969e+02,
       4.980e+00])

In [5]:
y = boston["target"]
print(y.shape)
y[0:10]

(506,)


array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9])

In [6]:
import pandas as pd

data = pd.DataFrame(X, columns=boston["feature_names"])
data["MEDV"] = y

print(data.shape)
data.head()

(506, 14)


CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  MEDV  
0     15.3  396.90   4.98  24.0  
1     17.8  396.90   9.14  21.6  
2     17.8  392.83   4.03  34.7  
3     18.7  394.63   2.94  33.4  
4     18.7  396.90   5.33  36.2

### Gradient Descent

In [9]:
x1 = X[:, 0] # CRIM
x2 = X[:, 1] # ZN
x3 = X[:, 2] # INDUS
x4 = X[:, 3] # CHAS
x5 = X[:, 4] # NOX
x6 = X[:, 5] # RM
x7 = X[:, 6] # AGE
x8 = X[:, 7] # DIS
x9 = X[:, 8] # RAD
x10 = X[:, 9] # TAX
x11 = X[:, 10] # PTRATIO
x12 = X[:, 11] # B
x13 = X[:, 12] # LSTAT
print(x1.shape)

(506,)


In [16]:
# your code here

# 여기에 Single-layer Neural Network 코드를 작성하여 보스턴 집값 문제를 풀어보세요!
def sigmoid(x, derivative=False):

  return x*(1-x) if derivative else 1/(1+np.exp(-x))

y = sigmoid(y)
# feature x1 ~ x13, 마지막 bias, label = y
w = np.random.uniform(low=-1.0, high=1.0) # 한 feature 에만 
num = 10000
learning_rate = 0.1
# 한개 씩 넣어본결과 상관관계를 가지는 변수는 x4, x5, x8
#x4
for b in range(num):
    
    y_pred = sigmoid(w*x4)
    error = np.abs(y-y_pred).mean()
    if(b%1000== 0) :
        print("error = {0:4.4f}".format(error))
    if(error < 0.0001) :
            break
    k = (np.transpose(y_pred-y)*x4).mean()
    w= w - k*learning_rate
w4 = w
print("w4 = ", w4)

#X4, X5
w = np.random.uniform(low=-1.0, high=1.0) # 한 feature 에만 
for b in range(num):
    
    y_pred = sigmoid(w4*x4 + w*x5)
    error = np.abs(y-y_pred).mean()
    if(b % 1000==0) :
        print("error = {0:4.4f}".format(error))
    if(error < 0.5) :
            break
    k = (np.transpose(y_pred-y)*x5).mean()
    w= w - k*learning_rate
    w4 = w4 - learning_rate * (np.transpose(y_pred-y)*x4).mean()
w5 = w
print("w5 = ", w5)

#x4, x5, x8
w = np.random.uniform(low=-1.0, high=1.0) # 한 feature 에만 
for b in range(num):
    
    y_pred = sigmoid(w4*x4 + w5*x5 + w*x8)
    error = np.abs(y-y_pred).mean()
    if(b%1000== 0) :
        print("error = {0:4.4f}".format(error))
    if(error < 0.0001) :
            break
    k = (np.transpose(y_pred-y)*x8).mean()
    w= w - k*learning_rate
    w4 = w4 - learning_rate * (np.transpose(y_pred-y)*x4).mean()
    w5 = w5 - learning_rate * (np.transpose(y_pred-y)*x5).mean()
w8 = w
print("w8 = ", w8)

#w4, w5, w8
bi = np.random.uniform(low=-1.0, high=1.0) # 한 feature 에만 
for b in range(100000):
    
    y_pred = sigmoid(w4*x4 + w5*x5 + w8*x8 +bi)
    error = np.abs(y-y_pred).mean()
    if(b%10000== 0) :
        print("error = {0:4.4f}".format(error))
    if(error < 0.0001) :
            break
    w4 = w4 - learning_rate * (np.transpose(y_pred-y)*x4).mean()
    w5 = w5 - learning_rate * (np.transpose(y_pred-y)*x5).mean()
    w8 = w8 - learning_rate * (np.transpose(y_pred-y)*x8).mean()
    bi = bi - learning_rate * (y_pred-y).mean()
print("w4 = {0:.5f}, w5 = {1:.5f}, w8 = {2:.5f}, bias = {3:.5f}".format(w4,w5,w8,bi))

# 번외 full model
bi = np.random.uniform(low=-1.0, high=1.0) # 한 feature 에만 
w1 =np.random.uniform(low=-1.0,high=1.0)
w2 =np.random.uniform(low=-1.0,high=1.0)
w3 =np.random.uniform(low=-1.0,high=1.0)
w6 =np.random.uniform(low=-1.0,high=1.0)
w7 =np.random.uniform(low=-1.0,high=1.0)
w9 =np.random.uniform(low=-1.0,high=1.0)
w10=np.random.uniform(low=-1.0,high=1.0)
w11=np.random.uniform(low=-1.0,high=1.0)
w12= np.random.uniform(low=-1.0,high=1.0)
w13= np.random.uniform(low=-1.0,high=1.0)
for b in range(10000):
    
    y_pred = sigmoid(w1*x1+w2*x2+w3*x3+ w4*x4 + w5*x5 +w6*x6+w7*x7+ w8*x8+w9*x9+w10*x10+w11*x11+w12*x12+w13*x13+bi)
    error = np.abs(y-y_pred).mean()
    if(b%1000== 0) :
        print("error = {0:4.4f}".format(error))
    if(error < 0.0001) :
            break
    w4 = w4 - learning_rate * (np.transpose(y_pred-y)*x4).mean()
    w5 = w5 - learning_rate * (np.transpose(y_pred-y)*x5).mean()
    w8 = w8 - learning_rate * (np.transpose(y_pred-y)*x8).mean()
    bi = bi - learning_rate * (y_pred-y).mean()
    w1 = w1 - learning_rate * (np.transpose(y_pred-y)*x1).mean()
    w2 = w2 - learning_rate * (np.transpose(y_pred-y)*x2).mean()
    w3 = w3 - learning_rate * (np.transpose(y_pred-y)*x3).mean()
    w6 = w6 - learning_rate * (np.transpose(y_pred-y)*x6).mean()
    w7 = w7 - learning_rate * (np.transpose(y_pred-y)*x7).mean()
    w9 = w9 - learning_rate * (np.transpose(y_pred-y)*x9).mean()
    w10 = w10 - learning_rate * (np.transpose(y_pred-y)*x10).mean()
    w11 = w11 - learning_rate * (np.transpose(y_pred-y)*x11).mean()
    w12 = w12 - learning_rate * (np.transpose(y_pred-y)*x12).mean()
    w13 = w13 - learning_rate * (np.transpose(y_pred-y)*x13).mean()
    
print("w4 = {0:.5f}, w5 = {1:.5f}, w8 = {2:.5f}, bias = {3:.5f}".format(w4,w5,w8,bi))


error = 0.1748
error = 0.1531
error = 0.1491
error = 0.1483
error = 0.1481
error = 0.1481
error = 0.1481
error = 0.1481
error = 0.1481
error = 0.1481
w4 =  0.6592266658857049
error = 0.1014
w5 =  0.3921722629551858
error = 0.1239
error = 0.0151
error = 0.0119
error = 0.0119
error = 0.0119
error = 0.0119
error = 0.0119
error = 0.0119
error = 0.0119
error = 0.0119
w8 =  0.04313790187891935
error = 0.0865
error = 0.0062
error = 0.0028
error = 0.0012
error = 0.0006
error = 0.0002
error = 0.0001
w4 = -0.00002, w5 = 0.00766, w8 = 0.00034, bias = 0.65366
error = 0.3801


C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: RuntimeWarning: overflow encountered in exp
  


error = 0.3409
error = 0.3409
error = 0.6591
error = 0.6591
error = 0.6591
error = 0.6591
error = 0.3409
error = 0.3409
error = 0.3409
w4 = 0.00203, w5 = 0.03065, w8 = 0.30318, bias = -0.25910


### Gradient Descent (use dot product)

만일 위의 과제가 너무 쉽다는 생각이 들면, **matrix의 [dot product](https://mathinsight.org/dot_product_matrix_notation)를 활용하여 문제를 풀어보세요.** dot product의 사용법은 다음과 같습니다.

In [1]:
X_temp = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print(X_temp.shape)
X_temp

(3, 3)


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [2]:
w_temp = np.array([2, 4, 8])

print(w_temp.shape)
w_temp

(3,)


array([2, 4, 8])

In [3]:
b_temp = np.array([0.1])

In [4]:
y_predict = X_temp.dot(w_temp) + b_temp

print(y_predict.shape)
y_predict

(3,)


array([  34.1,   76.1,  118.1])

In [8]:
# your code here
# 여기에 Single-layer Neural Network에 dot product를 활용하여 보스턴 집값 문제를 풀어보세요!

def sigmoid(x, derivative=False):
  return x*(1-x) if derivative else 1/(1+np.exp(-x))

# feature x1 ~ x13, 마지막 bias, label = y
y = sigmoid(y)
w = np.random.uniform(low=-1.0, high=1.0, size=13) # 한 feature 에만 
print(w.shape)
num = 10000
learning_rate = 0.1
# 한개 씩 넣어본결과 상관관계를 가지는 변수는 x4, x5, x8
#bias도 넣기

#x4
for b in range(num):
    
    y_pred = sigmoid(X.dot(w))
    error = np.abs(y-y_pred).mean()
    if(b%1000== 0) :
        print("w= ",w)
        print("error = {0:4.4f}".format(error))
    if(error < 0.0001) :
            break
    k = (np.transpose(y_pred-y).dot(X)).mean() #X.T.dot()
    w= w - k*learning_rate
w4 = w
print("final = ", w4)

# 나머지도 똑같이



(13,)
w=  [ 0.58981114  0.14606769  0.75291597 -0.03295832  0.25965231  0.75100666
 -0.4986964   0.40252591 -0.53727779  0.89647304  0.26967735  0.38507541
  0.87279557]
error = 0.2690


C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: RuntimeWarning: overflow encountered in exp
  """


w=  [157.85985435 157.41611091 158.02295919 157.2370849  157.52969552
 158.02104987 156.77134682 157.67256912 156.73276543 158.16651625
 157.53972057 157.65511862 158.14283878]
error = 0.2690
w=  [315.12989757 314.68615412 315.2930024  314.50712811 314.79973874
 315.29109309 314.04139003 314.94261234 314.00280864 315.43655947
 314.80976378 314.92516184 315.412882  ]
error = 0.2690
w=  [472.39994078 471.95619734 472.56304562 471.77717133 472.06978195
 472.5611363  471.31143325 472.21265555 471.27285186 472.70660268
 472.079807   472.19520505 472.68292521]
error = 0.2690
w=  [629.66998399 629.22624055 629.83308883 629.04721454 629.33982517
 629.83117952 628.58147646 629.48269877 628.54289507 629.9766459
 629.34985021 629.46524827 629.95296843]
error = 0.2690
w=  [786.94002721 786.49628377 787.10313205 786.31725776 786.60986838
 787.10122273 785.85151968 786.75274198 785.81293829 787.24668911
 786.61989343 786.73529148 787.22301164]
error = 0.2690
w=  [944.21007042 943.76632698 944.373175